import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { CartProvider } from '@/context/CartContext'
import { ReturnHome } from '@/components/ReturnHome'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <CartProvider>
        <body className={`${inter.className} text-white bg-black flex flex-col min-h-screen justify-center items-center`}>{children}</body>
        {/* <ReturnHome /> */}
      </CartProvider>
    </html>
  )
}
